vishalv971/CompetitiveCoding

.github/workflows/ccpp.yml
build.sh

Modified build.sh and yml

---

RAIIDemo.cpp

@pranjalkaler RAII concept demo. Please verify.

Resource Acquistion is Allocation demo

---

build.sh

Modified build file to handle all cpp files in all folders

---

DS/Set.cpp

@pranjalkaler  Solved the Set Introduction data structure campaign in Hackerearth. 
Trying to revive this dead repository.
Challenge Link: https://www.hackerrank.com/challenges/cpp-sets/problem?utm_campaign=challenge-recommendation&utm_medium=email&utm_source=7-day-campaign

Introduction to Set data structure

---

APOrNot.java

[Can Make Arithmetic Progression From Sequence](https://leetcode.com/problems/can-make-arithmetic-progression-from-sequence/)

Determine if array is arithematic progression

---

LeetCode/KthLargestElement.cpp

@pranjalkaler  Changed as intended , rebase and merge pls

Find the Kth largest element in the array

---

LeetCode/SumOfLeftLeaves.cpp

@pranjalkaler  and @SaumyaSachdev  do the honors

Sum of Left Leaves in Binary Tree

---

LeetCode/AddDigits.java

https://leetcode.com/problems/add-digits/

Calculate repeated digital sum of natural number

---

LeetCode/FirstUniqueCharacter.cpp

@SaumyaSachdev / @pranjalkaler  went for a fairly easy one because Friday

Find index of first unique character of string

---

LeetCode/CPP/LinkedListCycle.cpp

https://leetcode.com/problems/linked-list-cycle-ii/

Return node if LinkedList cycle exists

---

LeetCode/Java/SumRootToLeaf.java

[Sum root to leaf binary numbers](https://leetcode.com/problems/sum-of-root-to-leaf-binary-numbers/)

Sum root to leaf binary numbers

---

LeetCode/Java/NoOfSegments.java

[Number of Segments](https://leetcode.com/problems/number-of-segments-in-a-string/)

Count number of segments in string

---

LeetCode/CPP/NUniqueNumbersSumZero.cpp

https://leetcode.com/problems/find-n-unique-integers-sum-up-to-zero/

Program to find N unique numbers that sum to 0

---

LeetCode/CPP/ExcelSheetCodeNumber.cpp

https://leetcode.com/problems/excel-sheet-column-number/

Convert given String to corresponding Excel Sheet Column Number

---

LeetCode/Java/UglyNumber.java

[Ugly Number](https://leetcode.com/problems/ugly-number/)

Find if number divisble by only 2, 3, 5

---

LeetCode/Java/DestinationCity.java

https://leetcode.com/problems/destination-city/

Find destination city from paths

---

LeetCode/CPP/MaxKthSubArrayAvg.cpp

https://leetcode.com/problems/maximum-average-subarray-i/

Find average of the Maximum sub array of k size

---

LeetCode/CPP/IdenticalPairs.cpp

https://leetcode.com/problems/number-of-good-pairs/

Count the number of identical pairs in the array

---

LeetCode/Java/LongestPalindrome.java

https://leetcode.com/problems/longest-palindrome/submissions/

Calculate longest palindrome of a string

---

LeetCode/CPP/SecondMinNodeBinaryTree.cpp

https://leetcode.com/problems/second-minimum-node-in-a-binary-tree/

Second Minimum node in Binary Tree

---

LeetCode/CPP/ValidParantheses.cpp

LeetCode question: https://leetcode.com/problems/valid-parentheses/
@SaumyaSachdev @vishalv971 please review

Valid Parantheses using stack

---

LeetCode/Java/UncommonWords.java

https://leetcode.com/problems/uncommon-words-from-two-sentences/

Find unique words in two sentences

---

LeetCode/CPP/RunningSum.cpp

LeetCode: https://leetcode.com/problems/running-sum-of-1d-array/

Running Sum

---

LeetCode/CPP/KeyboardRow.cpp

https://leetcode.com/problems/keyboard-row

Find words that can be typed from a single row of the keyboard

---

LeetCode/Java/UniqueEmail.java

https://leetcode.com/problems/unique-email-addresses/

Find number of unique emails

---

LeetCode/Java/PivotIndex.java

https://leetcode.com/problems/find-pivot-index/

Sum of numbers on left equal to sum of nnumbers on the right

---

LeetCode/Java/MinimumTime.java

https://leetcode.com/problems/minimum-time-visiting-all-points/

Find minimum time required to visit given array of positions.

---

LeetCode/CPP/ConvertSortedArrayToBST.cpp

https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/
I am back at it :smile:

Convert a sorted array to a balanced BST

---

LeetCode/Java/WeakestRows.java

https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/ 
@vishalv971 @pranjalkaler

Find k weakest rows in a matrix

---

LeetCode/Java/RobotOrigin.java

https://leetcode.com/problems/robot-return-to-origin/

Judge whether a robot returns back to origin or not

---

LeetCode/CPP/CountPrimes.cpp

https://leetcode.com/problems/count-primes/

Count all Primes < n

---

LeetCode/Java/SingleNumberIII.java

https://leetcode.com/problems/single-number-iii/

Find two numbers which occur only once in an array

---

LeetCode/CPP/SerializeDeserializeBST.cpp

https://leetcode.com/problems/serialize-and-deserialize-bst

Serializing and DeSerializing the BST

---

build.sh

@SaumyaSachdev  / @pranjalkaler  
modifying the build script to compile only newly introduced files in the last 24 hours

Compiling only files modified in the last 24 hours

---

build.sh

Fixing build issues

---

LeetCode/CPP/BrowserHistory.cpp

https://leetcode.com/problems/design-browser-history

Browser History

---

LeetCode/Java/UnsortedSubarray.java

https://leetcode.com/problems/shortest-unsorted-continuous-subarray/

Find shortest unsorted subarray

---

LeetCode/CPP/PerfectSquare.cpp

Check whether a given number is a perfect square or not

---

LeetCode/Java/WordPattern.java

https://leetcode.com/problems/word-pattern/

Check if a string follows the given pattern

---

DS/Trie.cpp

Two commits are part of the same problem.

Trie data structure

---

LeetCode/CPP/PrimeSetBits.cpp

Prime Number of Set Bits in Binary form of number

---

LeetCode/Java/CousinsOrNot.java

https://leetcode.com/problems/cousins-in-binary-tree/

Check if two nodes are cousins or not in binary tree

---

LeetCode/CPP/SubDomainCount.cpp

https://leetcode.com/problems/subdomain-visit-count/

Find the count of the number of times sub domain has been visited

---

LeetCode/Java/SubtreeOrNot.java

https://leetcode.com/problems/subtree-of-another-tree/

Check if a tree is a subtree of another tree

---

LeetCode/CPP/DifferenceString.cpp

https://leetcode.com/problems/find-the-difference/

Find the difference between two strings

---

LeetCode/Java/LCIS.java

https://leetcode.com/problems/longest-continuous-increasing-subsequence/

Find the length of longest increasing subsequence

---

LeetCode/CPP/BuyOrSellStock.cpp

https://leetcode.com/problems/best-time-to-buy-and-sell-stock

Find max profit for given list of stock prices

---

LeetCode/Java/MaxCoins.java

https://leetcode.com/problems/maximum-number-of-coins-you-can-get/

Maximum number of coins you can get from a pile

---

LeetCode/CPP/JewelsAndStones.cpp

https://leetcode.com/problems/jewels-and-stones

Find count of stones that are jewels

---

LeetCode/Java/MergeBinaryTrees.java

https://leetcode.com/problems/merge-two-binary-trees/

Merge two given binary trees

---

LeetCode/CPP/LowestCommonAncestor.cpp

Find the lowest common ancestor BST

---

LeetCode/Java/MaxScore.java

https://leetcode.com/problems/maximum-score-after-splitting-a-string/

Find max score after splitting a string

---

LeetCode/CPP/ConstructRectangle.cpp

https://leetcode.com/problems/construct-the-rectangle

Construct Rectangle size from area

---

LeetCode/Java/TotalHammingDistance.java

https://leetcode.com/problems/total-hamming-distance/

Calculate total hamming distance between elements of an array

---

LeetCode/CPP/MyHashSet.cpp

https://leetcode.com/problems/design-hashset

Create custom implementation of HashSet

---

LeetCode/Java/NumberComplement.java

https://leetcode.com/problems/number-complement/

Find complement of a number

---

LeetCode/CPP/NextGreaterElement1.cpp

https://leetcode.com/problems/next-greater-element-i/
guys whoever merges delete the branch after merging 🥇

find the next greater element in 2 arrays

---

LeetCode/CPP/NextGreaterElement2.cpp

https://leetcode.com/problems/next-greater-element-ii/

Find next element greater in an circular array

---

Hackerrank/CPP/DayOfProgrammer.cpp

https://www.hackerrank.com/challenges/day-of-the-programmer/problem

Find the day of the programmer based on the conditions

---

LeetCode/Java/RobotInCircle.java

https://leetcode.com/problems/robot-bounded-in-circle/

Check if a robot is bounded in a circle with the given instructions

---

LeetCode/CPP/UniqueNumberOfOccurence.cpp

https://leetcode.com/problems/unique-number-of-occurrences/

Check if all numbers occur unique number of times

---

LeetCode/Java/OnlineStockSpan.java

https://leetcode.com/problems/online-stock-span/

Return span for each stock price

---

ALGOS/ConstExpr_In_Cpp.cpp
build.sh

Test for if cpp17 compiles or not

---

LeetCode/CPP/StringAnagram.cpp

https://leetcode.com/problems/find-all-anagrams-in-a-string/

Find all anagrams of string 2 in string 1

---

LeetCode/Java/RemoveDuplicate.java

https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/

Remove duplicates from a sorted array

---

LeetCode/CPP/PeakElement.cpp

https://leetcode.com/problems/find-peak-element

Find peak element in array

---

LeetCode/Java/DisappearedNumbers.java

https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/

Find missing numbers in the array

---

LeetCode/Java/GameWinner.java

https://leetcode.com/problems/find-the-winner-of-an-array-game/

Return integer which wins the game

---

LeetCode/CPP/SubSequence.cpp

https://leetcode.com/problems/number-of-matching-subsequences/

Find count of all matching subsequence

---

LeetCode/CPP/RepeatedDNA.cpp

https://leetcode.com/problems/repeated-dna-sequences

Find all repeated DNA sequences

---

LeetCode/Java/FlipImage.java

https://leetcode.com/problems/flipping-an-image/

Flip image horizontally and invert

---

LeetCode/CPP/LargestValueFromLabels.cpp

https://leetcode.com/problems/largest-values-from-labels/

Largest Value from labels

---

LeetCode/Java/ShuffleArray.java

https://leetcode.com/problems/shuffle-the-array/

Shuffle array accordingly

---

LeetCode/CPP/MaskPhoneAndEmail.cpp

A bit of this codebase probably resides in our company code base too
https://leetcode.com/problems/masking-personal-information/

Mask Phone or Email Address

---

LeetCode/CPP/StringCompression.cpp

Compress String based on input

---

LeetCode/CPP/SoldierRating.cpp

https://leetcode.com/problems/count-number-of-teams/

Soldier rating based on given conditions

---

LeetCode/Java/RotateFunction.java

https://leetcode.com/problems/rotate-function/

Find maximum value of the rotate function

---

LeetCode/CPP/PowerfulIntegers.cpp

https://leetcode.com/problems/powerful-integers

Powerful integers of the form x^i + y^j

---

LeetCode/Java/MergeLists.java

https://leetcode.com/problems/merge-two-sorted-lists/

Merge two sorted linked lists

---

LeetCode/CPP/SmallerThanCurrent.cpp

https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/

All numbers smaller than current number

---

LeetCode/CPP/GroupAnagram.cpp

https://leetcode.com/problems/group-anagrams/

Group all anagrams together
